default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: localhost
  username: root
  password: judoda09

development:
  <<: *default
  database: recipe_development
